// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAccountBalance = "account_balances"

// AccountBalance mapped from table <account_balances>
type AccountBalance struct {
	AccountID string  `gorm:"column:account_id;primaryKey" json:"account_id"`
	UserID    string  `gorm:"column:user_id" json:"user_id"`
	Amount    float64 `gorm:"column:amount" json:"amount"`
	DummyCol4 string  `gorm:"column:dummy_col_4" json:"dummy_col_4"`
}

// TableName AccountBalance's table name
func (*AccountBalance) TableName() string {
	return TableNameAccountBalance
}
