// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAccount = "accounts"

// Account mapped from table <accounts>
type Account struct {
	AccountID     string `gorm:"column:account_id;primaryKey" json:"account_id"`
	UserID        string `gorm:"column:user_id" json:"user_id"`
	Type          string `gorm:"column:type" json:"type"`
	Currency      string `gorm:"column:currency" json:"currency"`
	AccountNumber string `gorm:"column:account_number" json:"account_number"`
	Issuer        string `gorm:"column:issuer" json:"issuer"`
	DummyCol3     string `gorm:"column:dummy_col_3" json:"dummy_col_3"`
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
