// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAccountFlag = "account_flags"

// AccountFlag mapped from table <account_flags>
type AccountFlag struct {
	FlagID    int32     `gorm:"column:flag_id;primaryKey;autoIncrement:true" json:"flag_id"`
	AccountID string    `gorm:"column:account_id;not null" json:"account_id"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	FlagType  string    `gorm:"column:flag_type;not null" json:"flag_type"`
	FlagValue string    `gorm:"column:flag_value;not null" json:"flag_value"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName AccountFlag's table name
func (*AccountFlag) TableName() string {
	return TableNameAccountFlag
}
