// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAccountDetail = "account_details"

// AccountDetail mapped from table <account_details>
type AccountDetail struct {
	AccountID     string `gorm:"column:account_id;primaryKey" json:"account_id"`
	UserID        string `gorm:"column:user_id" json:"user_id"`
	Color         string `gorm:"column:color" json:"color"`
	IsMainAccount bool   `gorm:"column:is_main_account" json:"is_main_account"`
	Progress      int32  `gorm:"column:progress" json:"progress"`
	DummyCol5     string `gorm:"column:dummy_col_5" json:"dummy_col_5"`
}

// TableName AccountDetail's table name
func (*AccountDetail) TableName() string {
	return TableNameAccountDetail
}
