// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameBanner = "banners"

// Banner mapped from table <banners>
type Banner struct {
	BannerID    string `gorm:"column:banner_id;primaryKey" json:"banner_id"`
	UserID      string `gorm:"column:user_id" json:"user_id"`
	Title       string `gorm:"column:title" json:"title"`
	Description string `gorm:"column:description" json:"description"`
	Image       string `gorm:"column:image" json:"image"`
	DummyCol11  string `gorm:"column:dummy_col_11" json:"dummy_col_11"`
}

// TableName Banner's table name
func (*Banner) TableName() string {
	return TableNameBanner
}
