// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDebitCardStatus = "debit_card_status"

// DebitCardStatus mapped from table <debit_card_status>
type DebitCardStatus struct {
	CardID    string `gorm:"column:card_id;primaryKey" json:"card_id"`
	UserID    string `gorm:"column:user_id" json:"user_id"`
	Status    string `gorm:"column:status" json:"status"`
	DummyCol8 string `gorm:"column:dummy_col_8" json:"dummy_col_8"`
}

// TableName DebitCardStatus's table name
func (*DebitCardStatus) TableName() string {
	return TableNameDebitCardStatus
}
