// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDebitCardDetail = "debit_card_details"

// DebitCardDetail mapped from table <debit_card_details>
type DebitCardDetail struct {
	CardID     string `gorm:"column:card_id;primaryKey" json:"card_id"`
	UserID     string `gorm:"column:user_id" json:"user_id"`
	Issuer     string `gorm:"column:issuer" json:"issuer"`
	Number     string `gorm:"column:number" json:"number"`
	DummyCol10 string `gorm:"column:dummy_col_10" json:"dummy_col_10"`
}

// TableName DebitCardDetail's table name
func (*DebitCardDetail) TableName() string {
	return TableNameDebitCardDetail
}
