// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDebitCard = "debit_cards"

// DebitCard mapped from table <debit_cards>
type DebitCard struct {
	CardID    string `gorm:"column:card_id;primaryKey" json:"card_id"`
	UserID    string `gorm:"column:user_id" json:"user_id"`
	Name      string `gorm:"column:name" json:"name"`
	DummyCol7 string `gorm:"column:dummy_col_7" json:"dummy_col_7"`
}

// TableName DebitCard's table name
func (*DebitCard) TableName() string {
	return TableNameDebitCard
}
