// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDebitCardDesign = "debit_card_design"

// DebitCardDesign mapped from table <debit_card_design>
type DebitCardDesign struct {
	CardID      string `gorm:"column:card_id;primaryKey" json:"card_id"`
	UserID      string `gorm:"column:user_id" json:"user_id"`
	Color       string `gorm:"column:color" json:"color"`
	BorderColor string `gorm:"column:border_color" json:"border_color"`
	DummyCol9   string `gorm:"column:dummy_col_9" json:"dummy_col_9"`
}

// TableName DebitCardDesign's table name
func (*DebitCardDesign) TableName() string {
	return TableNameDebitCardDesign
}
