// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameTransaction = "transactions"

// Transaction mapped from table <transactions>
type Transaction struct {
	TransactionID string `gorm:"column:transaction_id;primaryKey" json:"transaction_id"`
	UserID        string `gorm:"column:user_id" json:"user_id"`
	Name          string `gorm:"column:name" json:"name"`
	Image         string `gorm:"column:image" json:"image"`
	IsBank        bool   `gorm:"column:isBank" json:"isBank"`
	DummyCol6     string `gorm:"column:dummy_col_6" json:"dummy_col_6"`
}

// TableName Transaction's table name
func (*Transaction) TableName() string {
	return TableNameTransaction
}
