// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID  string `gorm:"column:user_id;primaryKey" json:"user_id"`
	Name    string `gorm:"column:name" json:"name"`
	PinHash string `gorm:"column:pin_hash" json:"pin_hash"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
