// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserGreeting = "user_greetings"

// UserGreeting mapped from table <user_greetings>
type UserGreeting struct {
	UserID    string `gorm:"column:user_id;primaryKey" json:"user_id"`
	Greeting  string `gorm:"column:greeting" json:"greeting"`
	DummyCol2 string `gorm:"column:dummy_col_2" json:"dummy_col_2"`
}

// TableName UserGreeting's table name
func (*UserGreeting) TableName() string {
	return TableNameUserGreeting
}
